model:
  name: "hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4"
  api_base: "http://localhost:8000/v1"
  api_key: "dummy"

paths:
  summary:
    input: "df_text_by_report.csv"
    output:
      file: "results_down_sized/df_text_by_report_conversation_summary_less_label.csv"
      extend: False
  records:
    results:
      output:
        file: "results_down_sized/df_records_results.csv"
        extend: False
    states:
      output:
        file: "results_down_sized/df_records_states.csv"
        extend: False
    spans:
      output:
        file: "results_down_sized/df_records_spans.csv"
        extend: False
  classification:
    input: "results_down_sized/df_text_by_report_conversation_summary_less_label_consolidated.csv"
    output:
      file: "results_down_sized/df_text_by_report_conversation_classification.csv"
      extend: True
  eval:
    input: "results_down_sized/df_text_by_report_conversation_classification.csv"
    output:
      file: "results_down_sized/df_text_by_report_conversation_evaluation.csv"
  taxonomy: "config/taxonomy.json"
  prompts: "config/prompts.json"

async:
  enabled: True
  max_retries: 5
  max_concurrent_rows: 15
  max_concurrent_llm_calls: 50

processing:
  temperature: 0.0
  max_tokens_summary: 1024
  max_tokens_classification: 256
  start_index: 0
  summary_row_limit: null
  classification_key_limit: null
  conversation:
    enabled: True

evaluation:
  rows_eval_limit: null
  benchmarks:
    enable_geval_summarization: False
    enable_geval_hallucination: False
    enable_summac_zs: True
    enable_summac_conv: True
    enable_default_metrics: False

    summac_settings:
      device: "cuda"
      granularity: "sentence"
      model_name: "vitc"


display:
  use_progress_bar: True

logging:
  log_resources: False
  log_prompts: False
  log_response: False
  log_progress: True
  file: "processing.log"
