model:
  name: "hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4"
  api_base: "http://localhost:8000/v1"
  api_key: "dummy"

paths:
  summary:
    input: "df_text_by_report.csv"
    output:
      file: "df_text_by_report_conversation_summary.csv"
      extend: False
  classification:
    input: "df_text_by_report_conversation_summary.csv"
    output:
      file: "df_text_by_report_conversation_classification.csv"
      extend: False
  eval:
    input: "df_text_by_report_conversation_classification.csv"
    output:
      file: "df_text_by_report_conversation_evaluation.csv"
  taxonomy: "config/taxonomy.json"
  prompts: "config/prompts.json"

async:
  enabled: True
  max_retries: 5
  max_concurrent_rows: 20

processing:
  temperature: 0.0
  max_tokens_summary: 1024
  max_tokens_classification: 256
  start_index: 0
  summary_row_limit: null
  classification_key_limit: null
  conversation:
    enabled: True

evaluation:
  rows_eval_limit: null
  benchmarks:
    enable_geval_summarization: False
    enable_geval_hallucination: False
    enable_summac_zs: False
    enable_summac_conv: False
    enable_default_metrics: True

    summac_settings:
      device: "cuda"
      granularity: "sentence"
      model_name: "vitc"


display:
  use_progress_bar: True

logging:
  log_resources: false
  log_prompts: false
  log_response: true
  log_progress: True
  file: "processing.log"
